modName = CodeUtils
modVersion = 0.1.0
modId = codeutils
modGroup = com.mrleonardos.codeutils
useModGroupForPublishing = true
autoUpdateBuildScript = false
gtnh.modules.gitVersion = false

minecraftVersion = 1.7.10
forgeVersion = 10.13.4.1614
channel = stable
mappingsVersion = 12
remoteMappings = https\://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/

developmentEnvironmentUserName = Developer
enableModernJavaSyntax = jabel
enableGenericInjection = true

generateGradleTokenClass = com.mrleonardos.codeutils.Tags
gradleTokenVersion = VERSION
apiPackage = api

usesMixins = false
usesShadowedDependencies = false
includeWellKnownRepositories = true
usesMavenPublishing = true

org.gradle.configuration-cache = true
org.gradle.parallel = true
